# -*- coding: utf-8 -*-
"""Pandas_practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15vODqcJW4ceHiDkYxgDTGIk-2A5leG7_
"""

import pandas as pd
import numpy as np

#series is similar to numpy array
lables=['a','b','c']
my_data=[10,20,30]
arr=np.array(my_data)
d={'a':10,'b':20,'c':30}

pd.Series(data=my_data)

pd.Series(data=my_data,index=lables)
pd.Series(my_data,lables)

pd.Series(d)
pd.Series(arr)

ser1=pd.Series([1,2,3,4],['USA','GERMANY','USSR','JAPAN'])
ser1

ser2=pd.Series([1,2,5,4],['USA','GERMANY','ITALY','JAPAN'])
ser2

ser1['USA']

ser1+ser2
#pandas converts to float to retain data

from numpy.random import randn

np.random.seed(101)

df=pd.DataFrame(randn(5,4),['a','b','c','d','e'],['w','x','y','z'])
df

df['w']
type(df['w'])

df[['w','z']]

df['new'] = df['w']+df['y']
df['new']

#axis=0 - index - rows
#axis=1 - index - columns
#inplace=True is used to permenently delete data from df like confirmation
df.drop('new',axis=1,inplace=True)
df

df.drop('e')

df.shape
df.loc['a']

#returns the 2nd row
df.iloc[2]

df.loc[['a','b'],['w','y']]

booldf=df>0
booldf

df[booldf]

df[df>0]
df

df['w']>0

df[df['w']>0]

df[df['w']>0]['x']

df[df['w']>0][['x','y']]

#AND = &  and OR= |
df[(df['w']>0) | (df['x']>0)]

df.reset_index()
df

newind='CA NY WY OR CO'.split()

newind

df['States']=newind
df

#if we specify then it will make that as index
df.set_index('States')

def times2(x):
  return X*2

df['col3'].apply(lambda x:x*2)

df.drop('col1',axis=1,inplace=true)

df.columns
df.index
df.sort_values('col2')
df.isnull()
df.pivot_table(values='D',index=['A','B'],columns=['c'])

pd.read_csv('example.csv')

df=pd.read_csv('example.csv')
df.to_csv('My_output',index=False)

df=pd.read_excel('Excel_Sample.xlsx')

df.to_excel('sample_1.xlsx')

from sqlalchemy import create_engine
engine = create_engine('sqllite:///:memory:')

